Changed over to:  automake (GNU automake) 1.5 autoconf (GNU Autoconf) 2.53

diff --git a/admin/missing b/admin/missing
--- a/admin/missing
+++ b/admin/missing
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Common stub for a few missing GNU programs while installing.
-# Copyright (C) 1996, 1997, 1999 Free Software Foundation, Inc.
+# Copyright 1996, 1997, 1999, 2000 Free Software Foundation, Inc.
 # Originally by Fran,cois Pinard <pinard@iro.umontreal.ca>, 1996.
 
 # This program is free software; you can redistribute it and/or modify
@@ -18,19 +18,88 @@
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 # 02111-1307, USA.
 
+# As a special exception to the GNU General Public License, if you
+# distribute this file as part of a program that contains a
+# configuration script generated by Autoconf, you may include it under
+# the same distribution terms that you use for the rest of that program.
+
 if test $# -eq 0; then
   echo 1>&2 "Try \`$0 --help' for more information"
   exit 1
 fi
 
-run=:
+# In the cases where this matters, `missing' is being run in the
+# srcdir already.
+if test -f configure.ac; then
+  configure_ac=configure.ac
+else
+  configure_ac=configure.in
+fi
 
 case "$1" in
 --run)
   # Try to run requested program, and just exit if it succeeds.
   run=
   shift
-  "$@" && exit 0
+  exec="$@"
+
+  ## KEEP IN SYNC WITH cvs.sh!!
+  ### Handle special autoconf cases first.
+  if test -x /usr/bin/autoconf-2.53 ; then
+     AUTOCONF="/usr/bin/autoconf-2.53"
+  elif test -x /usr/bin/autoconf-2.52 ; then
+     AUTOCONF="/usr/bin/autoconf-2.52"
+  elif test -x /usr/bin/autoconf2.50 ; then
+     AUTOCONF="/usr/bin/autoconf2.50"
+  else
+     AUTOCONF="autoconf"
+  fi
+  export AUTOCONF
+
+  if test -x /usr/bin/autoheader-2.53 ; then
+     AUTOHEADER="/usr/bin/autoheader-2.53"
+     AUTOM4TE="/usr/bin/autom4te-2.53"
+  elif test -x /usr/bin/autoheader-2.52 ; then
+     AUTOHEADER="/usr/bin/autoheader-2.52"
+  elif test -x /usr/bin/autoheader2.50 ; then
+     AUTOHEADER="/usr/bin/autoheader2.50"
+  else
+     AUTOHEADER="autoheader"
+  fi
+  export AUTOM4TE
+  export AUTOHEADER
+
+  if test -z "$UNSERMAKE"; then
+    if test -x /usr/bin/automake-1.5 ; then
+       AUTOMAKE="/usr/bin/automake-1.5"
+       ACLOCAL="/usr/bin/aclocal-1.5"
+    else
+       AUTOMAKE="automake"
+       ACLOCAL="aclocal"
+    fi
+  else
+    AUTOMAKE="$UNSERMAKE"
+    ACLOCAL="aclocal"
+  fi
+
+  export AUTOMAKE
+  export ACLOCAL
+
+  case "$1" in
+  aclocal)
+    exec="`echo $exec|sed -e \"s^aclocal^$ACLOCAL^\"`"
+    ;;
+  autoheader)
+    exec="`echo $exec|sed -e \"s^autoheader^$AUTOHEADER^\"`"
+    ;; 
+  autoconf)
+    exec="`echo $exec|sed -e \"s^autoconf^$AUTOCONF^\"`"
+    ;;
+  automake)
+    exec="`echo $exec|sed -e \"s^automake^$AUTOMAKE^\"`"
+    ;;
+  esac
+  $exec && exit 0
   ;;
 esac
 
@@ -57,6 +126,7 @@ Supported PROGRAM values:
   automake     touch all \`Makefile.in' files
   bison        create \`y.tab.[ch]', if possible, from existing .[ch]
   flex         create \`lex.yy.c', if possible, from existing .c
+  help2man     touch the output file
   lex          create \`lex.yy.c', if possible, from existing .c
   makeinfo     touch the output file
   tar          try tar, gnutar, gtar, then tar without non-portable flags
@@ -64,7 +134,7 @@ Supported PROGRAM values:
     ;;
 
   -v|--v|--ve|--ver|--vers|--versi|--versio|--version)
-    echo "missing 0.2 - GNU automake"
+    echo "missing 0.3 - GNU automake"
     ;;
 
   -*)
@@ -76,7 +146,7 @@ Supported PROGRAM values:
   aclocal)
     echo 1>&2 "\
 WARNING: \`$1' is missing on your system.  You should only need it if
-         you modified \`acinclude.m4' or \`configure.in'.  You might want
+         you modified \`acinclude.m4' or \`${configure_ac}'.  You might want
          to install the \`Automake' and \`Perl' packages.  Grab them from
          any GNU archive site."
     touch aclocal.m4
@@ -85,7 +155,7 @@ WARNING: \`$1' is missing on your system.  You should only need it if
   autoconf)
     echo 1>&2 "\
 WARNING: \`$1' is missing on your system.  You should only need it if
-         you modified \`configure.in'.  You might want to install the
+         you modified \`${configure_ac}'.  You might want to install the
          \`Autoconf' and \`GNU m4' packages.  Grab them from any GNU
          archive site."
     touch configure
@@ -94,10 +164,10 @@ WARNING: \`$1' is missing on your system.  You should only need it if
   autoheader)
     echo 1>&2 "\
 WARNING: \`$1' is missing on your system.  You should only need it if
-         you modified \`acconfig.h' or \`configure.in'.  You might want
+         you modified \`acconfig.h' or \`${configure_ac}'.  You might want
          to install the \`Autoconf' and \`GNU m4' packages.  Grab them
          from any GNU archive site."
-    files=`sed -n 's/^[ ]*A[CM]_CONFIG_HEADER(\([^)]*\)).*/\1/p' configure.in`
+    files=`sed -n 's/^[ ]*A[CM]_CONFIG_HEADER(\([^)]*\)).*/\1/p' ${configure_ac}`
     test -z "$files" && files="config.h"
     touch_files=
     for f in $files; do
@@ -113,7 +183,7 @@ WARNING: \`$1' is missing on your system.  You should only need it if
   automake)
     echo 1>&2 "\
 WARNING: \`$1' is missing on your system.  You should only need it if
-         you modified \`Makefile.am', \`acinclude.m4' or \`configure.in'.
+         you modified \`Makefile.am', \`acinclude.m4' or \`${configure_ac}'.
          You might want to install the \`Automake' and \`Perl' packages.
          Grab them from any GNU archive site."
     find . -type f -name Makefile.am -print |
@@ -174,7 +244,32 @@ WARNING: \`$1' is missing on your system.  You should only need it if
     fi
     ;;
 
+  help2man)
+    echo 1>&2 "\
+WARNING: \`$1' is missing on your system.  You should only need it if
+	 you modified a dependency of a manual page.  You may need the
+	 \`Help2man' package in order for those modifications to take
+	 effect.  You can get \`Help2man' from any GNU archive site."
+
+    file=`echo "$*" | sed -n 's/.*-o \([^ ]*\).*/\1/p'`
+    if test -z "$file"; then
+	file=`echo "$*" | sed -n 's/.*--output=\([^ ]*\).*/\1/p'`
+    fi
+    if [ -f "$file" ]; then
+	touch $file
+    else
+	test -z "$file" || exec >$file
+	echo ".ab help2man is required to generate this page"
+	exit 1
+    fi
+    ;;
+
   makeinfo)
+    if test -z "$run" && (makeinfo --version) > /dev/null 2>&1; then
+       # We have makeinfo, but it failed.
+       exit 1
+    fi
+
     echo 1>&2 "\
 WARNING: \`$1' is missing on your system.  You should only need it if
          you modified a \`.texi' or \`.texinfo' file, or any other file
@@ -197,9 +292,15 @@ WARNING: \`$1' is missing on your system.  You should only need it if
       exit 1
     fi
 
-    # we have already tried tar in the generic part
-    gnutar ${1+"$@"} && exit 0
-    gtar ${1+"$@"} && exit 0
+    # We have already tried tar in the generic part.
+    # Look for gnutar/gtar before invocation to avoid ugly error
+    # messages.
+    if (gnutar --version > /dev/null 2>&1); then
+       gnutar ${1+"$@"} && exit 0
+    fi
+    if (gtar --version > /dev/null 2>&1); then
+       gtar ${1+"$@"} && exit 0
+    fi
     firstarg="$1"
     if shift; then
 	case "$firstarg" in
